### ISSUE TITLE
Ingredient/Measurements & Non-Alcoholic

### ISSUE THREAD

**Issue by ashlenbruns** [ScottTAnderson/Project-1#8]
I'm having trouble getting all of the ingredients and all of the measurements to show up on the card. Only the first ingredient and first measurement appear. I also need to think about how each ingredient will occupy its own line (using <br> somewhere?).

Scott, we will run across an issue with the api as it is coded now if the user selects non-alcoholic.  From the documentation, it looks like it needs to be a= instead of i= for all of our other choices.

**Comment by ScottTAnderson** [comment]
This might be another limitation of the API altogether. That's again on me. I'm looking into it and I will provide a solution as soon as one presents itself.

**Comment by ScottTAnderson** [comment]
Both issued addressed. Created pull request. Code is near-final.
